/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_accumulation_imageblurring_app_jni_ImageBlur */

#ifndef _Included_com_accumulation_imageblurring_app_jni_ImageBlur
#define _Included_com_accumulation_imageblurring_app_jni_ImageBlur
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_accumulation_imageblurring_app_jni_ImageBlur
	* Method:    blur
	* Signature: ([IIII)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_accumulation_imageblurring_app_jni_ImageBlur_blurIntArray
		(JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_accumulation_imageblurring_app_jni_ImageBlur
	* Method:    blur
	* Signature: ([IIII)[I
	*/
	JNIEXPORT void JNICALL Java_com_accumulation_imageblurring_app_jni_ImageBlur_blurBitMap
		(JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif
